//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aSkyImage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aSkyImage.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string AlbumPageAppBarDownload {
            get {
                return ResourceManager.GetString("AlbumPageAppBarDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string AlbumPageAppBarUpload {
            get {
                return ResourceManager.GetString("AlbumPageAppBarUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string AlbumPageAppBarZoom {
            get {
                return ResourceManager.GetString("AlbumPageAppBarZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please give your album a name.
        /// </summary>
        public static string AlbumsPageAddNewAlbumsName {
            get {
                return ResourceManager.GetString("AlbumsPageAddNewAlbumsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Album.
        /// </summary>
        public static string AlbumsPageAppBarAddAlbum {
            get {
                return ResourceManager.GetString("AlbumsPageAppBarAddAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your albums.
        /// </summary>
        public static string AlbumsPageTitle {
            get {
                return ResourceManager.GetString("AlbumsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aSkyImage.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to start.
        /// </summary>
        public static string CommonPinToStart {
            get {
                return ResourceManager.GetString("CommonPinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string CommonRefresh {
            get {
                return ResourceManager.GetString("CommonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session ended, please login.
        /// </summary>
        public static string LoginPromptTitle {
            get {
                return ResourceManager.GetString("LoginPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string MainPageAppBarAlbums {
            get {
                return ResourceManager.GetString("MainPageAppBarAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded, move to albums.
        /// </summary>
        public static string MainPageStatusLoadedAlbums {
            get {
                return ResourceManager.GetString("MainPageStatusLoadedAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading your albums...
        /// </summary>
        public static string MainPageStatusLoadingAlbums {
            get {
                return ResourceManager.GetString("MainPageStatusLoadingAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting login.
        /// </summary>
        public static string MainPageStatusPleaseLogin {
            get {
                return ResourceManager.GetString("MainPageStatusPleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string MainPageStatusTitle {
            get {
                return ResourceManager.GetString("MainPageStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start browsing your SkyDrive albums and photos by login with your Microsoft credentials..
        /// </summary>
        public static string MainPageWelcomeInfo {
            get {
                return ResourceManager.GetString("MainPageWelcomeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to aSkyImage!.
        /// </summary>
        public static string MainPageWelcomeText {
            get {
                return ResourceManager.GetString("MainPageWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New album created.
        /// </summary>
        public static string MessageToUserAlbumCreated {
            get {
                return ResourceManager.GetString("MessageToUserAlbumCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New comment added to a photo.
        /// </summary>
        public static string MessageToUserCommentAdded {
            get {
                return ResourceManager.GetString("MessageToUserCommentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo {0} downloaded to your phone..
        /// </summary>
        public static string MessageToUserDownloadingCompleted {
            get {
                return ResourceManager.GetString("MessageToUserDownloadingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image uploaded.
        /// </summary>
        public static string MessageToUserImageUploaded {
            get {
                return ResourceManager.GetString("MessageToUserImageUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a photo first.
        /// </summary>
        public static string MessageToUserPleaseSelectPhotoFirst {
            get {
                return ResourceManager.GetString("MessageToUserPleaseSelectPhotoFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with selected album...
        /// </summary>
        public static string MessageToUserProblemsWithAlbum {
            get {
                return ResourceManager.GetString("MessageToUserProblemsWithAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading image to album: {0}.
        /// </summary>
        public static string MessageToUserUploadingImageToAlbum {
            get {
                return ResourceManager.GetString("MessageToUserUploadingImageToAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your comment.
        /// </summary>
        public static string PhotoPageAddCommentTitle {
            get {
                return ResourceManager.GetString("PhotoPageAddCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string PhotoPageAppBarAddNewComment {
            get {
                return ResourceManager.GetString("PhotoPageAppBarAddNewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not shared, go to your skydrive www to share the image..
        /// </summary>
        public static string PhotoPageImageCommentingDisabled {
            get {
                return ResourceManager.GetString("PhotoPageImageCommentingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comments..
        /// </summary>
        public static string PhotoPageImageHasNoComments {
            get {
                return ResourceManager.GetString("PhotoPageImageHasNoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PromptCancel {
            get {
                return ResourceManager.GetString("PromptCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string PromptOk {
            get {
                return ResourceManager.GetString("PromptOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tile exists already..
        /// </summary>
        public static string TileExistsAlready {
            get {
                return ResourceManager.GetString("TileExistsAlready", resourceCulture);
            }
        }
    }
}
